# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander J. Dufford, PhD
email: alexander.dufford@yale.edu
description: > # this means to ignore newlines until "baseurl:"
  Researcher at the Intersection of Developmental Psychology, Machine Learning, and Neuroimaging
baseurl: 
url: 

# Social media profiles - feel free to add more here
twitter_username: ajdneuro
github_username:  ajdneuro12
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://



# Build settings
markdown: kramdown
